package main

import (
	"log"
	"net"
	"net/http"

	"github.com/budougumi0617/sandbox_goswagger/controller"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {
	l, err := net.Listen("tcp", ":18080")
	if err != nil {
		log.Fatalln(err)
	}
	server := controller.NewServer(l)

	done := make(chan struct{})
	go func() {
		log.Printf("server start %q", server.Listener.Addr().String())
		if err := server.Start(); err != http.ErrServerClosed {
			log.Printf("shutdown failed %v", err)
		}
		done <- struct{}{}
	}()

	// シグナルを受け付けるコードを書く

	<-done
}
