swagger: '2.0'
info:
  version: 0.0.0
  title: Sample API

paths:
  /api/register:
    post:
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: hoge_id
          in: query
          description: クエリパラメータ
          type: integer
          required: true
        - in: body
          name: user
          description: The user to create.
          schema:
            $ref: '#/definitions/RegisterRequestBody'
      responses:
        200:
          description: ok
        404:
          description: Data Not Found
  /hello:
    get:
      produces:
        - application/json
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to World if not given
      operationId: getGreeting
      responses:
        200:
          description: returns a greeting
          schema:
            $ref: "#/definitions/HelloResponse"

definitions:
  RegisterRequestBody:
    type: object
    description: オブジェクトを別に定義してみるサンプル1
    required:
      - name
    properties:
      name:
        type: string
      firstName:
        type: string
      lastName:
        type: string
  HelloResponse: # テンプレート名
    type: "object"
    description: オブジェクトを別に定義してみるサンプル
    properties:
      name:
        type: "string"
        example: "john due"